### ISSUE TITLE
New Reciter -  Qari Abdulrhman Mosad

### ISSUE THREAD

**Issue by iamtalhaasghar** [AlfaazPlus/QuranApp#144]
Can we add audios for whole quran from this very famous reciter, [Qari Abdulrhman Mosad](https://www.youtube.com/watch?v=tJ3c4Y3QNII).

Problem: There isn't complete Quran recitation available from this Qari on internet.

Solution: We can train an AI model on existing audios available and then let that model to convert all Quran text to his amazing voice and then we can add it to this app.

I can train such model but i dont have enough resources / GPUs.

What do you guys think? Are there any ethical implications if we are using his AI generated voice without his consent?

I've been thinking about this for a long time and I think this is the best place to start. Hence, i wrote down this long post.

May Allah bless us all in this world and world hereafter. Aameen.

Ramadan Mubarak!

**Comment by faisalcodes** [comment]
I listened to him, his voice is amazing. To add a new reciter in the QuranApp, all the audios should be available verse by verse and should be hosted somewhere. Since audios of his complete recitation is not available, we can't currently add it.

Regarding his consent on AI generated audios, probably nobody would say "yes" to this. Because there are several aspects of a recitation like tajweed, style, speed, correctness, AI would not be able to do that. But we can try though. I don't have such resources either, so probably I cannot do much.

> May Allah bless us all in this world and world hereafter. Aameen.

Aameen

**Comment by amrelhossieny** [comment]
I really hope hearing his voice in the next update
